# Generated by Django 5.1.7 on 2025-04-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floresvalentin_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialorder',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='occasion',
            field=models.CharField(choices=[('cumpleanos', 'Cumpleaños'), ('aniversario', 'Aniversario'), ('boda', 'Boda'), ('condolencias', 'Condolencias'), ('agradecimiento', 'Agradecimiento'), ('nacimiento', 'Nacimiento'), ('otro', 'Otro')], default='otro', max_length=100),
        ),
    ]
