# Generated by Django 5.1.7 on 2025-05-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floresvalentin_app', '0003_alter_specialorder_delivery_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido Especial', 'verbose_name_plural': 'Pedidos Especiales'},
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Dirección de entrega'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='delivery_city',
            field=models.CharField(max_length=50, verbose_name='Ciudad de entrega'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='delivery_date',
            field=models.DateField(verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal de entrega'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hora de entrega'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensaje para la tarjeta'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='occasion',
            field=models.CharField(choices=[('cumpleanos', 'Cumpleaños'), ('aniversario', 'Aniversario'), ('boda', 'Boda'), ('condolencias', 'Condolencias'), ('agradecimiento', 'Agradecimiento'), ('nacimiento', 'Nacimiento'), ('otro', 'Otro')], default='otro', max_length=100, verbose_name='Ocasión'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='products',
            field=models.JSONField(blank=True, help_text='Descripción o lista de productos deseados', null=True, verbose_name='Productos deseados'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='recipient_name',
            field=models.CharField(max_length=150, verbose_name='Nombre del destinatario'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del destinatario'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='special_instructions',
            field=models.TextField(blank=True, verbose_name='Instrucciones especiales'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_progress', 'En Progreso'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
