# Generated by Django 5.1.7 on 2025-05-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floresvalentin_app', '0008_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
